apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
  metadata:
    name: hello-nginx
    namespace: default
    spec:
      containers:
        - name: nginx
          image: localhost:5000/hello-nginx:latest
          ports:
            - containerPort: 80
