apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      nodeName: servidor1
      containers:
        - name: nginx
          image: localhost:5000/hello-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
