apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8083
  type: NodePort
