apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
